# Generated by Django 5.1.2 on 2024-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='recommendations',
            field=models.JSONField(default=list, verbose_name='추천 시나리오'),
        ),
    ]
